[package]
name = "darkbio-clock"
version = "0.3.0"
authors = ["Péter Szilágyi <peter@dark.bio>"]
description = "Virtual clock for testing blocking code"
repository = "https://github.com/dark-bio/clock-rs"
documentation = "https://docs.rs/darkbio-clock"
categories = ["development-tools::testing", "date-and-time"]
keywords = ["clock", "time", "testing", "virtual-time", "dark-bio"]
license = "BSD-3-Clause"
edition = "2024"
rust-version = "1.85"
exclude = ["lint/"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage_nightly)", "cfg(loom)"] }

[features]
default = []
test-clock = []
crossbeam = ["dep:crossbeam-channel"]

[dependencies]
crossbeam-channel = { version = "0.5.17", optional = true }

[dev-dependencies]
proptest = { version = "1.11.0", default-features = false, features = ["std"] }

[target.'cfg(loom)'.dev-dependencies]
loom = "0.7.2"
